### ISSUE TITLE
Cannot reach TestController "Index" method. Ambiguity between page names and controller index methods.

### ISSUE THREAD

**Issue by dduplantis** [htdnug/sports#15]
**Describe the bug**
A clear and concise description of what the bug is.z

When a controller has the same name as a page, and contains a "default" action method (currently "Index"), the action method is truncated from the URL and the Page is accessed instead of the Index method on the controller.

**To Reproduce**
1. Create a Page of any name.
2. Create a controller of the same name.
3. Create an action method which corresponds to the default route mapped action method.
4. Navigate to the newly created action method, even explicitly including the action method in the URL.

**Expected behavior**
Navigation to the controller's default method.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7 Professional
 - Browser Firefox Nightly
 - Version 67.0a1

**Additional context**
This is caused by "Index" being the default action method in the route mapper. This overlaps with the new ASP.NET Core Page routing.

**Comment by knight0323** [comment]
As discussed in last meeting,
